# Lesson outline

* Create a NumPy array:
  * from a pandas dataframe: pandas.DataFrame.values
  * from a Python sequence: numpy.array
  * with constant initial values: numpy.ones, numpy.zeros
  * with random values: numpy.random
* Access array attributes: shape, ndim, size, dtype
* Compute statistics: sum, min, max, mean
* Carry out arithmetic operations: add, subtract, multiply, divide
* Measure execution time: time.time, profile
* Manipulate array elements: Using simple indices and slices, integer arrays, boolean arrays

**Dataframe is just wrapper for numpy ndarray**

`nd1=df1.values`

![](img/1.png)

In [43]:
import numpy as np

# List to 1D array
print(np.array([2, 3, 4]))

# 2D array
print(np.array([[1,2,3], [5,6,7]]))

# empty array (actually not zero)
print(np.empty((5,4,3)))

# array of 1s
print(np.ones((5, 4)))

[2 3 4]
[[1 2 3]
 [5 6 7]]
[[[-1.28822975e-231 -1.29073963e-231  2.21540947e-314]
  [ 2.19770998e-314  2.21541545e-314  2.21542364e-314]
  [ 2.21542450e-314  2.21542471e-314  2.21542478e-314]
  [ 2.21542485e-314  2.21542492e-314  2.21259782e-314]]

 [[ 2.21539882e-314  2.21542500e-314  2.21535712e-314]
  [ 2.21542514e-314  2.21534827e-314  2.21542521e-314]
  [ 2.21533723e-314  2.21542528e-314  2.21539904e-314]
  [ 2.21542535e-314  2.21541924e-314  2.21542549e-314]]

 [[ 2.21541914e-314  2.21542557e-314  2.21539923e-314]
  [ 2.19624299e-314  2.21543579e-314  2.21533176e-314]
  [ 2.21543586e-314  2.21533180e-314  2.21543593e-314]
  [ 2.21534831e-314  2.21543600e-314  2.21535123e-314]]

 [[ 2.21543607e-314  2.21533824e-314  2.21543614e-314]
  [ 2.21535715e-314  2.21543621e-314  2.21535119e-314]
  [ 2.19619391e-314  2.21543628e-314  2.21543384e-314]
  [ 2.21543643e-314  2.21533719e-314  2.21543657e-314]]

 [[ 2.21533183e-314  2.21543671e-314  2.21533173e-314]
  [ 2.21543692e-314  2.2153385

In [44]:
# generating random values
np.random.random((5,4))  # random() uniformly sampled from [0.0, 1.0)

array([[0.68606763, 0.94171111, 0.12454798, 0.43670109],
       [0.12649632, 0.17646316, 0.15994133, 0.23114565],
       [0.85053995, 0.2732834 , 0.56136226, 0.80309824],
       [0.02816901, 0.34656847, 0.52476857, 0.7780763 ],
       [0.2852825 , 0.09296586, 0.18428266, 0.27587949]])

In [45]:
# Sample numbers from a Gausian (normal) distribution (mean = 0, s.d. = 1)
print(np.random.normal(size=(2,3)))

print(np.random.normal(10, 5, size=(2,3)))  # (mean = 10, s.d. = 5)

[[-0.68290101 -0.08248873 -0.12057103]
 [-1.01855804 -1.379017   -0.41547778]]
[[13.72503131 17.48526006 10.92626148]
 [ 0.59646251  8.54334655 14.99610304]]


In [46]:
# array attributes

# shape of the array
a = np.random.rand(5, 4)
print(a.shape)

# number of elems in the array
print(a.size)

# data type of the values
print(a.dtype)

(5, 4)
20
float64


In [47]:
# Operations on ndarrays

np.random.seed(693)
a = np.random.randint(0, 10, size=(5,4)) # 5x4 random integers in [0, 10)
print(a)

print(a.sum()) # sum of all elements

print(f"sum of each column:{a.sum(axis=0)}")  # Iterate over rows, to compute sum of each column
print(f"sum of each row:{a.sum(axis=1)}")  # Iterate over columns, to compute sum of each row
print(f"mean of all elements:{a.mean()}")  # Mean of all elements

[[2 0 5 1]
 [1 3 4 4]
 [9 2 9 1]
 [9 3 7 5]
 [4 7 0 3]]
79
sum of each column:[25 15 25 14]
sum of each row:[ 8 12 21 24 14]
mean of all elements:3.95


In [48]:
# accessing using list of indices

a = np.random.rand(5)
print(a)
indices = np.array([1, 1, 2, 3])
print(a[indices])

[0.31127579 0.62872047 0.07569968 0.54876981 0.53860522]
[0.62872047 0.62872047 0.07569968 0.54876981]


In [49]:
# Boolean or mask index arrays

a = np.array([(20,25,10,23,26,32,10,5,0), (0,2,50,20,0,1,28,5,0)])
print(a)
mean = a.mean()
print(mean)

print(a[a<mean])

[[20 25 10 23 26 32 10  5  0]
 [ 0  2 50 20  0  1 28  5  0]]
14.277777777777779
[10 10  5  0  0  2  0  1  5  0]


In [50]:
# Arithmetic operations

a = np.array([(1,2,3,4,5),(10,20,30,40,50)])
print(f"Multiply a by 2: \n{2*a}")

Multiply a by 2: 
[[  2   4   6   8  10]
 [ 20  40  60  80 100]]


In [51]:
# two arrays with same dimension => element-wise ops

a = np.array([1,2,3])
b = np.array([10,11,12])
a*b

array([10, 22, 36])